title: Kiki's Delivery
description: Documentation for the Kiki's Delivery project for Orbital AY23/24
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
