title: Kikis Delivery
description: Documentation for the Kikis Delivery project for Orbital AY23/24
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

baseurl: "/jekyll_just-the-docs_test"
url: ""

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
